### ISSUE TITLE
Github Filter for Owners only.

### ISSUE THREAD

**Issue by liyanchang** [alex/otp-cop#4]
Error when running Github check on non-organization owners.
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ExpectedError("Array", "{\"documentation_url\":\"https://developer.github.com/v3/orgs/members/#audit-two-factor-auth\",\"message\":\"Only owners can use this filter.\"}")', ../src/libcore/result.rs:731
```
The [github docs](https://developer.github.com/v3/orgs/members/#audit-two-factor-auth) does seem to document that the 2-factor auth filter is limited to organization owners.

I'm not sure that there is any way to get around this so you can close this with a short note in the README.

**Comment by alex** [comment]
I think there's two actions items here:

- [ ] document in the README that the user must be an owner
- [ ] have the process give a readable error, instead of ... that

**Comment by liyanchang** [comment]
So looking into this on the slack side as well:

Github will return an error on the request - there isn't a good way to [check ownership](http://stackoverflow.com/questions/20144295/github-api-v3-determine-if-user-is-an-owner-of-an-organization) so catching the error makes sense.

On the slack side, it will just not answer the question - `has_2fa` is just not present in the member list without error.

So for slack, I think that if you want to avoid having people email everyone in their org besides them:
1. finding your username
2. checking if that user is an admin

(I suppose you can also check that if only one user has `has_2fa` present, that's also an indicator that you're not an admin)

```
#[derive(RustcDecodable)]
struct SlackAuthTestResponse {
    ok: bool,
    user_id: String,
}

#[derive(RustcDecodable)]
struct SlackUserInfoResponse {
    ok: bool,
    user: SlackUser,
}
```

```
let client = Client::new();
let mut response = client.get(
    &format!("https://slack.com/api/auth.test?token={}", token)
).send().unwrap();
assert_eq!(response.status, StatusCode::Ok);
let mut body = String::new();
response.read_to_string(&mut body).unwrap();

let result = json::decode::<SlackAuthTestResponse>(&body).unwrap();
assert!(result.ok);
println!("{}", result.user_id);

let mut response = client.get(
    &format!("https://slack.com/api/users.info?token={}&user={}",
    token, result.user_id)
).send().unwrap();
assert_eq!(response.status, StatusCode::Ok);
let mut body = String::new();
response.read_to_string(&mut body).unwrap();
let result = json::decode::<SlackUserInfoResponse>(&body).unwrap();
assert!(result.ok);
return result.user.is_admin.unwrap();
```
